In [ ]:
import pandas as pd

# Step 1: Read CSV file

In [ ]:
import pandas as pd
df = pd.read_csv('./dataset/pima-indians-diabetes.csv')

# Step 2: Print the first 5 row

In [ ]:
df.head(5) #head(10)

# from back --> tail()

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

# Step 3: Print only 'bmi' column

In [ ]:
df['bmi']

0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
5      25.6
6      31.0
7      35.3
8      30.5
9       0.0
10     37.6
11     38.0
12     27.1
13     30.1
14     25.8
15     30.0
16     45.8
17     29.6
18     43.3
19     34.6
20     39.3
21     35.4
22     39.8
23     29.0
24     36.6
25     31.1
26     39.4
27     23.2
28     22.2
29     34.1
       ...
738    36.6
739    39.5
740    42.3
741    30.8
742    28.5
743    32.7
744    40.6
745    30.0
746    49.3
747    46.3
748    36.4
749    24.3
750    31.2
751    39.0
752    26.0
753    43.3
754    32.4
755    36.5
756    32.0
757    36.3
758    37.5
759    35.5
760    28.4
761    44.0
762    22.5
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: bmi, Length: 768, dtype: float64

# Step 4: Print number of row in this dataset

In [ ]:
print(df.shape)
df.shape[0] #row
df.shape[1] #col

(768, 9)

768

# Step 5: Print the name of all the columns

In [ ]:
df.columns

Index(['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree',
       'age', 'label'],
      dtype='object')

# Step 6: Print 13th bmi

In [ ]:
print(df.head(15))

print('13th BMI:',df['bmi'][12])

    pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0          6      148  72    35        0  33.6     0.627   50      1
1          1       85  66    29        0  26.6     0.351   31      0
2          8      183  64     0        0  23.3     0.672   32      1
3          1       89  66    23       94  28.1     0.167   21      0
4          0      137  40    35      168  43.1     2.288   33      1
5          5      116  74     0        0  25.6     0.201   30      0
6          3       78  50    32       88  31.0     0.248   26      1
7         10      115   0     0        0  35.3     0.134   29      0
8          2      197  70    45      543  30.5     0.158   53      1
9          8      125  96     0        0   0.0     0.232   54      1
10         4      110  92     0        0  37.6     0.191   30      0
11        10      168  74     0        0  38.0     0.537   34      1
12        10      139  80     0        0  27.1     1.441   57      0
13         1      189  60    23      846  30.1     0.398   59      1
14         5      166  72    19      175  25.8     0.587   51      1
13th BMI: 27.1

# Step 7: Print bmi in 3th row

In [ ]:
print(df.iloc[2])
print("======")
print(df.iloc[2]) # index
print("======")
print(df.loc[2,'bmi']) #label

pregnant      8.000
glucose     183.000
bp           64.000
skin          0.000
insulin       0.000
bmi          23.300
pedigree      0.672
age          32.000
label         1.000
Name: 2, dtype: float64
======
pregnant      8.000
glucose     183.000
bp           64.000
skin          0.000
insulin       0.000
bmi          23.300
pedigree      0.672
age          32.000
label         1.000
Name: 2, dtype: float64
23.3

# Step 8: Print bmi >=30 (show only first five column)

In [ ]:
df[ df['bmi']>=30 ].head()

# Print bmi >=3 (3-4筆)
df[df['bmi']>=30 ][3:5]

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
4         0      137  40    35      168  43.1     2.288   33      1
6         3       78  50    32       88  31.0     0.248   26      1
7        10      115   0     0        0  35.3     0.134   29      0
8         2      197  70    45      543  30.5     0.158   53      1

# Step 9: Calculate mean of age

In [ ]:
df['age'].mean()

33.240885416666664

# Step 10: Create a new column call "magic_number" and each row of magic number equal bmi plus age

In [ ]:
df['magic_number'] = df['bmi'] + df['age']

In [ ]:
df.head()

,pregnant,glucose,bp,skin,insulin,bmi,pedigree,age,label,magic_number
0,6,148,72,35,0,33.6,0.627,50,1,83.6
1,1,85,66,29,0,26.6,0.351,31,0,57.6
2,8,183,64,0,0,23.3,0.672,32,1,55.3
3,1,89,66,23,94,28.1,0.167,21,0,49.1
4,0,137,40,35,168,43.1,2.288,33,1,76.1